### ISSUE TITLE
MKL: remove :name: with GUID

### ISSUE THREAD

**Issue by rscohn2** [oneapi-src/oneAPI-spec#111]
The :name: with GUID are introduced by conversion from DITA, but are not used
   .. container:: section
      :name: GUID-753F13BA-A3C7-4F24-90F1-14B6279BD95C

**Comment by spencerpatty** [comment]
as of 8/31/2020, we have the following GUID still in our oneMKL project:  

./source/elements/oneMKL/source/domains/rng/mkl-rng-leapfrog.rst:75:.. |image0| image:: ../equations/GUID-D90F2CB0-58B4-42F5-A1F9-FD1EA859DD44-low.png
./source/elements/oneMKL/source/domains/rng/mkl-rng-skip_ahead.rst:117:.. |image0| image:: ../equations/GUID-061AF9F8-B166-4154-9BF1-4E2C99F1CE1F-low.png
./source/elements/oneMKL/source/domains/vm/cdfnorm.rst:261:.. |image0| image:: ../equations/GUID-0B9A59CC-C914-429D-AF87-93B16DABD291-low.jpg
./source/elements/oneMKL/source/domains/vm/cdfnorminv.rst:283:.. |image0| image:: ../equations/GUID-8C1F2803-8F8F-4795-BF16-41856C6442CF-low.jpg
./source/elements/oneMKL/source/domains/vm/erf.rst:278:.. |image0| image:: ../equations/GUID-0B9A59CC-C914-429D-AF87-93B16DABD291-low.jpg
./source/elements/oneMKL/source/domains/vm/erfc.rst:300:.. |image0| image:: ../equations/GUID-0B9A59CC-C914-429D-AF87-93B16DABD291-low.jpg
./source/elements/oneMKL/source/domains/vm/erfcinv.rst:285:.. |image0| image:: ../equations/GUID-8C1F2803-8F8F-4795-BF16-41856C6442CF-low.jpg
./source/elements/oneMKL/source/domains/vm/erfinv.rst:300:.. |image0| image:: ../equations/GUID-8C1F2803-8F8F-4795-BF16-41856C6442CF-low.jpg

**Comment by spencerpatty** [comment]
Just checked and at least some of the listed cases here are still a part of our source code and need to be fixed. @paveldyakov can you please have your team take a look at rng.  I will reach out to VM team as well.

**Comment by paveldyakov** [comment]
@spencerpatty, in both RNG files we used the images, that are called as GUID-D90F2CB0-58B4-42F5-A1F9-FD1EA859DD44-low.png and GUID-061AF9F8-B166-4154-9BF1-4E2C99F1CE1F-low.png. 

Could you please clarify the problem? Should we change these names?

**Comment by spencerpatty** [comment]
@paveldyakov yes please, give it a readable name.

**Comment by paveldyakov** [comment]
@spencerpatty sure! will do

**Comment by rscohn2** [comment]
Can we close this issue?

**Comment by paveldyakov** [comment]
These two were renamed:
./source/elements/oneMKL/source/domains/rng/mkl-rng-leapfrog.rst:75:.. |image0| image:: ../equations/GUID-D90F2CB0-58B4-42F5-A1F9-FD1EA859DD44-low.png
./source/elements/oneMKL/source/domains/rng/mkl-rng-skip_ahead.rst:117:.. |image0| image:: ../equations/GUID-061AF9F8-B166-4154-9BF1-4E2C99F1CE1F-low.png

I am not sure about other

**Comment by spencerpatty** [comment]
@zettai-reido and @hdelassus could you take a look at the remaining GUID image references in vm domain and rename them to something more meaningful?  Thanks!

**Comment by hdelassus** [comment]
@spencerpatty Thanks for notifying us, I'll take a look!

**Comment by hdelassus** [comment]
@spencerpatty I renamed the two GUID references and files in the equations directory directly related to the VM domain. There are 62 binary files in this directory that are never referenced. It may be time to remove them. For instance, `GUID-CA113DF0-DE46-42A1-99AF-93F6F76E72EA-low.gif` was used in the LAPACK domain, but replaced by inline LaTeX math.

**Comment by spencerpatty** [comment]
> @spencerpatty I renamed the two GUID references and files in the equations directory directly related to the VM domain. There are 62 binary files in this directory that are never referenced. It may be time to remove them. For instance, `GUID-CA113DF0-DE46-42A1-99AF-93F6F76E72EA-low.gif` was used in the LAPACK domain, but replaced by inline LaTeX math.

Hi @hdelassus I agree, that is the next step once we rename the ones we want to keep, I will go in and delete the rest :)  Actually if you are already preparing a PR for your changes, would you be ok with deleting the ones that are not referenced anywhere as well ?

**Comment by hdelassus** [comment]
@spencerpatty Sure, I'll do that real quick in another PR

**Comment by hdelassus** [comment]
@spencerpatty Can this issue be closed now? It seems we have fixed everything related.

**Comment by spencerpatty** [comment]
@hdelassus yes looks like it. Let us close this issue as resolved.
