### ISSUE TITLE
MKL: spec refers to product manual

### ISSUE THREAD

**Issue by rscohn2** [oneapi-src/oneAPI-spec#114]
Check that these links are appropriate. In general, we should not refer to product docs.

./elements/oneMKL/source/domains/dft/mkl-dft-descriptor-mkl-dft-precision-mkl-dft-domain-commit.rst:66:         Functions <https://software.intel.com/en-us/onemkl-developer-refer\
ence-c-status-checking-functions>`__
./elements/oneMKL/source/domains/dft/mkl-dft-descriptor-mkl-dft-precision-mkl-dft-domain-computebackward-typename-iotype.rst:45:         `transform <https://software.intel.com/en\
-us/onemkl-developer-reference-c-fourier-transform-functions#FORMULA>`__
./elements/oneMKL/source/domains/dft/mkl-dft-descriptor-mkl-dft-precision-mkl-dft-domain-computebackward-typename-iotype.rst:61:         C/C++ <https://software.intel.com/en-us/o\
nemkl-developer-reference-c-configuring-and-computing-an-fft-in-c-c>`__.
./elements/oneMKL/source/domains/dft/mkl-dft-descriptor-mkl-dft-precision-mkl-dft-domain-computebackward-typename-iotype.rst:66:         Functions <https://software.intel.com/en-\
us/onemkl-developer-reference-c-status-checking-functions>`__
./elements/oneMKL/source/domains/dft/mkl-dft-descriptor-mkl-dft-precision-mkl-dft-domain-computeforward-typename-iotype.rst:44:         `transform <https://software.intel.com/en-\
us/onemkl-developer-reference-c-fourier-transform-functions#FORMULA>`__
./elements/oneMKL/source/domains/dft/mkl-dft-descriptor-mkl-dft-precision-mkl-dft-domain-computeforward-typename-iotype.rst:60:         C/C++ <https://software.intel.com/en-us/on\
emkl-developer-reference-c-configuring-and-computing-an-fft-in-c-c>`__.
./elements/oneMKL/source/domains/dft/mkl-dft-descriptor-mkl-dft-precision-mkl-dft-domain-computeforward-typename-iotype.rst:65:         Functions <https://software.intel.com/en-u\
s/onemkl-developer-reference-c-status-checking-functions>`__
./elements/oneMKL/source/domains/dft/mkl-dft-descriptor-mkl-dft-precision-mkl-dft-domain-getvalue.rst:44:         `DftiGetValue <https://software.intel.com/en-us/onemkl-developer\
-reference-c-dftigetvalue#BC7944B8-F01C-40C4-8EAA-6C3422C9C838>`__
./elements/oneMKL/source/domains/dft/mkl-dft-descriptor-mkl-dft-precision-mkl-dft-domain-getvalue.rst:58:         Functions <https://software.intel.com/en-us/onemkl-developer-ref\
erence-c-status-checking-functions>`__
./elements/oneMKL/source/domains/dft/mkl-dft-descriptor-mkl-dft-precision-mkl-dft-domain-setvalue.rst:44:         Params <https://software.intel.com/en-us/onemkl-developer-refere\
nce-c-dftisetvalue>`__.
./elements/oneMKL/source/domains/dft/mkl-dft-descriptor-mkl-dft-precision-mkl-dft-domain-setvalue.rst:78:         `DftiSetValue <https://software.intel.com/en-us/onemkl-developer\
-reference-c-dftisetvalue#7E6778F1-D80D-4CED-82F4-90CF4600FA57>`__.
./elements/oneMKL/source/domains/dft/mkl-dft-descriptor-mkl-dft-precision-mkl-dft-domain-setvalue.rst:83:         Functions <https://software.intel.com/en-us/onemkl-developer-ref\
erence-c-status-checking-functions>`__

**Comment by spencerpatty** [comment]
we plan to have this fixed for 0.9 release

**Comment by mkrainiuk** [comment]
Fixed in 0.9 release
