### ISSUE TITLE
Implicit capture of `this` pointer via `[=]`

### ISSUE THREAD

**Issue by WeiqunZhang** [oneapi-src/oneAPI-spec#127]
[Implicit capture of `this` pointer via`[=]` has been deprecated in C++ 20](http://eel.is/c++draft/depr#capture.this).  For many codes, it's almost always a bug when `this` is implicitly captured onto device.  This kind of bugs can be quite hard to track down.  Could DPC++ deprecate this before C++20 is fully supported?  Could DPC++ compiler provide options to generate warning or error on this specific deprecation?

**Comment by Pennycook** [comment]
An error for implicit capture of `this` in SYCL kernels was just merged in https://github.com/intel/llvm/pull/2029.  @WeiqunZhang, could you please take a look and close this if the changes there are sufficient?

**Comment by WeiqunZhang** [comment]
That's great! Thanks!
