### ISSUE TITLE
Memory fence

### ISSUE THREAD

**Issue by WeiqunZhang** [oneapi-src/oneAPI-spec#130]
In the current spec, there is only memory fence in the scope of work group,  could oneAPI support memory fence in the device scope and in the scope of SVM devices (like OpenCL 2.0)?

**Comment by Pennycook** [comment]
The latest update to the ExtendedAtomics extension in https://github.com/intel/llvm/pull/1584 includes a new `memory_scope` enum that can be passed to an `atomic_fence` function:

```c++
enum class memory_scope : /* unspecified */ {
  work_item, sub_group, work_group, device, system
};
inline constexpr memory_scope memory_scope_work_item = memory_scope::work_item;
inline constexpr memory_scope memory_scope_sub_group = memory_scope::sub_group;
inline constexpr memory_scope memory_scope_work_group = memory_scope::work_group;
inline constexpr memory_scope memory_scope_device = memory_scope::device;
inline constexpr memory_scope memory_scope_system = memory_scope::system;

void atomic_fence(memory_order order, memory_scope scope);
```

`atomic_fence(..., memory_scope::device)` acts as a memory fence at device scope, and `atomic_fence(..., memory_scope::system)` act as a memory fence across all devices that can see the same buffers/USM allocations as the device executing the fence.  SYCL/DPC++ don't have the concept of "SVM devices", but this is pretty close.

Is the functionality specified in https://github.com/intel/llvm/pull/1584 sufficient, or is there some functionality missing?

**Comment by WeiqunZhang** [comment]
Yes, the functionality specified in intel/llvm#1584 is sufficient.  Thanks!
