### ISSUE TITLE
Math does not render properly in Internet Explorer

### ISSUE THREAD

**Issue by outoftardis** [oneapi-src/oneAPI-spec#169]
Math formulas do not render properly in Internet Explorer, e.g. for [this page](https://spec.oneapi.com/versions/latest/elements/oneDAL/source/algorithms/nearest_neighbors/knn_classification.html):

![image](https://user-images.githubusercontent.com/17865025/86899426-a92b9800-c112-11ea-911d-b9edf3c09290.png)

---

Note: formulas in oneDAL product docs work just fine in Internet Explorer

**Comment by outoftardis** [comment]
@rlnx @rscohn2 I don't have an immediate answer as to why this happens, do you know how to fix this?

**Comment by rscohn2** [comment]
It is using mathjax, and the doc says you need to add some html to get it to work with IE11

http://docs.mathjax.org/en/latest/output/browser.html

**Comment by rscohn2** [comment]
Closing. Works for Edge
