### ISSUE TITLE
DPL: Description of 'Specific API'

### ISSUE THREAD

**Issue by rscohn2** [oneapi-src/oneAPI-spec#25]
Can you write some text to describe algorithms for 'Specific API of oneDPL' If there is a product manual, you can copy from it.

From Timmie:

> Yes, I can add that to the section. The description is where I'll also describe the optional parameters to the algorithms, e.g., initial values, comparators, etc. that @akukanov suggested earlier this week to reduce the number of functions we list in this section.

**Comment by akukanov** [comment]
Finally done in v0.9
