### ISSUE TITLE
ormqr() documentation mismatch

### ISSUE THREAD

**Issue by mkstoyanov** [oneapi-src/oneAPI-spec#301]
**Read my next post**

Originally I got confused by the `ormqr()`, `ormrq()` and the LAPACK `ormql()` methods. I elaborated on the confusion and the problems with OneMKL in my next post. I will keep the original post for reference purposes, although it is probably useless.

*old comment below, replace ormqr with ormrq and it will make more sense*

The documentation of `ormqr()` is inconsistent with LAPACK, probably documentation error:

* the `trans` parameter is said to apply `Q` when `trans` and `Q^T` when `nontrans`, which is inconsistent at best
* the `n` parameter is said to relate to the number of columns of `A`, which is redundant with `k`
* there is no way to indicate the number of columns of `C`

Check the netlib documentation for reference.

https://www.netlib.org/lapack/explore-html/da/dba/group__double_o_t_h_e_rcomputational_ga17b0765a8a0e6547bcf933979b38f0b0.html

**Comment by mkstoyanov** [comment]
I wasted days until I realized how bad this this.

OneMKL has two methods `ormqr()` and `ormrq()`, which correspond to two different factorizations. It is extremely difficult to distinguish between the `rq` and `qr` in a large section of code, especially if you don't expect that may be an issue.

The LAPACK standard introduces the `dgelqf()` and `dormlq()` to distinguish between the left and right versions of QR. There is no danger of an error, since a different character is used (L as opposed to R).

However, the OneMKL documentation is not consistent with LQ either:

https://docs.oneapi.com/versions/latest/onemkl/ormrq.html

https://github.com/oneapi-src/oneAPI-spec/blob/main/source/elements/oneMKL/source/domains/lapack/ormrq.rst

Compare those to:

https://www.netlib.org/lapack/explore-html/da/dba/group__double_o_t_h_e_rcomputational_ga99147464f79c5447c08eead5a06a90ce.html

In the OneMKL version, the `m` and `n` correspond to the size of `A` while `k` is the number of `tau` factors of `Q`, which is actually `min(m, n)` and hence redundant. The OneMKL API  has no way of specifying the number of rows of `C`, e.g., QR and LQ are often used to solve over/under determined least-squares problems and the number of rows correspond to the number of right-hand-sides which can be completely arbitrary.

**Comment by sknepper** [comment]
Hello,
Thanks for the detailed issue!  We're sorry for the frustration you've experienced.  We'll take a look to see what can be done to improve the specification.

**Comment by mkstoyanov** [comment]
Hello @sknepper 
the specification is one side of the problem, on the other the current documentation for the `ormRQ()` and `urmRQ()` is not correct and the methods don't work properly.

Thanks for looking into this.

**Comment by ericlars** [comment]
Hi @mkstoyanov
> * the trans parameter is said to apply Q when trans and Q^T when nontrans, which is inconsistent at best
> * the n parameter is said to relate to the number of columns of A, which is redundant with k
> * there is no way to indicate the number of columns of C

These are indeed errors in the documentation. I suggest referring to the [netlib documentation](https://www.netlib.org/lapack/explore-html/da/dba/group__double_o_t_h_e_rcomputational_ga99147464f79c5447c08eead5a06a90ce.html) until these are corrected.

There may be some confusion on the different orthogonal factorizations provided by LAPACK, there are four families, QR, LQ, RQ, and QL. Currently oneMKL provides interfaces for QR and RQ families, but not LQ or QL. Routines from different orthogonalization families should not be mixed.
