### ISSUE TITLE
namespace oneapi::std is a bad idea

### ISSUE THREAD

**Issue by akukanov** [oneapi-src/oneAPI-spec#304]
oneDPL specifications v1.0 says (https://spec.oneapi.com/versions/1.0/elements/oneDPL/source/common.html) that "oneDPL uses ``namespace oneapi::std`` for the subset of the standard C++ library for kernels". In practice, this turned out to be a bad idea, because this namespace hides the standard ``namespace std`` for any code within ``namespace oneapi``, i.e. for all oneAPI libraries, resulting in the need to use double colons for the standard classes & functons, Because of this issue, Intel's implementation of oneDPL does not yet provide this namespace.

The recommendation is to remove ``namespace oneapi::std`` from the specification. It's an incompatible change technically, but since there is no implementation providing this namespace, the removal should have no impact on any real code.

**Comment by rscohn2** [comment]
Out of an abundance of caution, I asked Alexey to post something here so other teams could comment. I agree with Alexey that we should proceed.

**Comment by andreynv** [comment]
The recommendation makes sense to me

**Comment by akukanov** [comment]
Fixed by PR https://github.com/oneapi-src/oneAPI-spec/pull/305
