### ISSUE TITLE
VPL: Clear doxygen warnings

### ISSUE THREAD

**Issue by rscohn2** [oneapi-src/oneapi-spec#32]
Please try to clear all the doxygen warnings.
`cd source/elements/oneVPL`
`  doxygen Doxyfile
/build/source/elements/oneVPL/include/vplmemory/vplm.h:339: warning: explicit link request to 'vplm_mem' could not be resolved
/build/source/elements/oneVPL/include/vplmemory/vplm.h:339: warning: explicit link request to 'vplm_mem' could not be resolved
/build/source/elements/oneVPL/include/vpl/vpl.hpp:30: warning: argument 'optional' of command @param is not found in the argument list \
of vpl::Decode::Decode(VplFourCC src_format, VplTargetDevice device=VPL_TARGET_DEVICE_DEFAULT)
/build/source/elements/oneVPL/include/vpl/vpl.hpp:35: warning: The following parameter of vpl::Decode::Decode(VplFourCC src_format, Vpl\
TargetDevice device=VPL_TARGET_DEVICE_DEFAULT) is not documented:
  parameter 'device'
/build/source/elements/oneVPL/include/vplmemory/vplm.h:339: warning: explicit link request to 'vplm_mem' could not be resolved
/build/source/elements/oneVPL/include/vplmemory/vplm.h:339: warning: explicit link request to 'vplm_mem' could not be resolved
/build/source/elements/oneVPL/include/vpl/vpl.hpp:30: warning: argument 'optional' of command @param is not found in the argument list \
of vpl::Decode::Decode(VplFourCC src_format, VplTargetDevice device=VPL_TARGET_DEVICE_DEFAULT)
/build/source/elements/oneVPL/include/vpl/vpl.hpp:35: warning: The following parameter of vpl::Decode::Decode(VplFourCC src_format, Vpl\
TargetDevice device=VPL_TARGET_DEVICE_DEFAULT) is not documented:
  parameter 'device'
/build/source/elements/oneVPL/include/vplmemory/vplm.h:294: warning: explicit link request to 'vplm_on_destroy_cb' could not be resolve\
d
/build/source/elements/oneVPL/include/vplmemory/vplm.h:45: warning: explicit link request to '_vplm_status' could not be resolved
<unknown>:1: warning: explicit link request to 'vplm_mem' could not be resolved
/build/source/elements/oneVPL/include/vplmemory/vplm.h:319: warning: explicit link request to 'info' could not be resolved
/build/source/elements/oneVPL/include/vplmemory/vplm.h:320: warning: explicit link request to 'info' could not be resolved
/build/source/elements/oneVPL/include/vplmemory/vplm.h:324: warning: explicit link request to 'vplm_create_from_cpu_image' could not be\
 resolved
/build/source/elements/oneVPL/include/vplmemory/vplm.h:368: warning: explicit link request to 'vplm_unref' could not be resolved
/build/source/elements/oneVPL/include/vplmemory/vplm.h:380: warning: explicit link request to 'VPLM_PROPERTY_CALLBACK_ON_DESTROY' could\
 not be resolved
/build/source/elements/oneVPL/include/vplmemory/vplm_opencl.h:102: warning: explicit link request to 'vplm_cl_begin_image_access' could\
 not be resolved
/build/source/elements/oneVPL/include/vplmemory/vplm_opencl.h:102: warning: explicit link request to 'vplm_cl_end_image_access' could n\
ot be resolved
/build/source/elements/oneVPL/include/vplmemory/vplm_vaapi.h:59: warning: explicit link request to 'vplm_cl_begin_image_access' could n\
ot be resolved
/build/source/elements/oneVPL/include/vplmemory/vplm_vaapi.h:59: warning: explicit link request to 'vplm_cl_end_image_access' could not\
 be resolved
`

**Comment by pengtu** [comment]
Fixed in the oneVPL branch.
