### ISSUE TITLE
MKL: add comment about APIs with multiple USM inputs, all USM pointers should be of same type

### ISSUE THREAD

**Issue by spencerpatty** [oneapi-src/oneAPI-spec#327]
@mkrainiuk @petercad Does it make sense to add to our USM section a comment about APIs with multiple USM inputs needing to have all of them created with the same malloc_XXX api ?

**Comment by petercad** [comment]
Hey @spencerpatty -- Actually, I think we should allow mixed USM pointer types in the same call. On the implementation side, it shouldn't be too hard to support, right? For some BLAS APIs, in fact, it will be best to have some USM pointers reside on the host and some on the device, for optimal performance.

**Comment by spencerpatty** [comment]
@petercad Can you be more specific about what use cases this might be important for?   I am thinking about sparse domain where we may have three arrays for each matrix rowPtr, colInd and values  which should all exist in the same places...  Although now that I am thinking about it,  possibly the rowPtr could be only on host...
