### ISSUE TITLE
DNN: sphinx warnings 

### ISSUE THREAD

**Issue by rscohn2** [oneapi-src/oneapi-spec#34]
python ../../../scripts/element.py html

Ignore the RemovedInSphinx30 warnings, but please fix these or let me know if you would rather I look at them.

`/localdisk/work/rscohn1/Projects/spec/oneapi-spec/source/elements/oneDNN/source/index.rst:100: WARNING: Duplicate declaration, dnnl::me\
mory::undef
/localdisk/work/rscohn1/Projects/spec/oneapi-spec/source/elements/oneDNN/source/index.rst:100: WARNING: Duplicate declaration, dnnl::un\
def
/localdisk/work/rscohn1/Projects/spec/oneapi-spec/source/elements/oneDNN/source/index.rst:100: WARNING: Duplicate declaration, dnnl::un\
def
/localdisk/work/rscohn1/Projects/spec/oneapi-spec/source/elements/oneDNN/source/index.rst:100: WARNING: Duplicate declaration, dnnl::un\
def
/localdisk/work/rscohn1/Projects/spec/oneapi-spec/source/elements/oneDNN/source/index.rst:100: WARNING: Duplicate declaration, dnnl::en\
gine
`

**Comment by rsdubtso** [comment]
I'll look into these.

**Comment by rsdubtso** [comment]
I am not able to fix those (and adding groups -- the thing that we discussed makes things even worse). I think this is a sphinx / doxygen bug. I'll ask InfoDev to take it from here, probably.

**Comment by rscohn2** [comment]
It's this https://github.com/michaeljones/breathe/issues/470

The page displays OK: https://spec.oneapi.com/versions/latest/elements/oneDNN/source/index.html#_CPPv4N4dnnl6memory10format_tagE

So the warning is harmless. Thanks for looking at it.
