### ISSUE TITLE
MKL: roadmap milestones

### ISSUE THREAD

**Issue by rscohn2** [oneapi-src/oneAPI-spec#37]
Populate roadmap.rst with some milestones. For example 1st drop of API descriptions in RST. Final drop.

**Comment by trosenqu** [comment]
Our stretch goal is to have 1st drop of API descriptions at end of March. That just misses 0.7.0, but would easily make 0.8.0. 

I hope to be able to communicate a solid plan in 2 weeks.

**Comment by rscohn2** [comment]
ISC 6/28 will be a good opportunity for getting feedback. Having a solid draft at 0.8.0 on 5/28 will make it possible for us to distribute to labs/universities/companies before hand. I am going to add MKL draft suitable for review to the 0.8.0 milestone.

**Comment by mkrainiuk** [comment]
Roadmap for MKL was defined
