### ISSUE TITLE
oneMKL device routine usage model

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/oneAPI-spec#419]
Can you please provide a usage model for random-number-generators-device-routines ?  Thanks.

**Comment by sknepper** [comment]
Hello! Thank you for your interest in RNG device routines. The oneMKL specification currently does not contain device APIs for random number generators. However, the Intel oneMKL 2022.1 product release does, and it also ships some examples for these device APIs as well.
The release can be downloaded here: https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl-download.html
The examples can be extracted from the examples_dpcpp tarball and will then be located in the dpcpp_device folder.
You can also find documentation for these APIs here: https://www.intel.com/content/www/us/en/develop/documentation/oneapi-mkl-dpcpp-developer-reference/top/random-number-generators/random-number-generators-device-routines.html

We would welcome any feedback you would have on these device APIs! Thank you.

**Comment by zjin-lcf** [comment]
Thanks.
