### ISSUE TITLE
Issue on page /elements/oneMKL/source/domains/blas/syrk.html

### ISSUE THREAD

**Issue by jakub-homola** [oneapi-src/oneAPI-spec#462]
`oneapi::mkl::blas::syrk` - input parameters - the description of the `upper_lower` parameter states

> Specifies whether `A`’s data is stored in its upper or lower triangle. ...

but it should probably be 

> Specifies whether `C`’s data ...

this appears both at the buffer and the USM version.

the version of the docs I am seeing is 1.2-rev-1

**Comment by mmeterel** [comment]
@jakub-homola The fix is merged. Thanks again for catching. Closing this issue. Please re-open if needed.
