### ISSUE TITLE
Issue on page /elements/oneMKL/source/domains/blas/trsv.html

### ISSUE THREAD

**Issue by jakub-homola** [oneapi-src/oneAPI-spec#475]
There is an extra parameter `k` that should not be there (or a missing description of `k`, but I suppose the former is more likely). Applies to both buffer and USM versions.

Same problem with [intel's docs](https://www.intel.com/content/www/us/en/develop/documentation/oneapi-mkl-dpcpp-developer-reference/top/blas-routines/blas-level-2-routines/trsv.html), but that will probably be fixed automatically when this spec will be fixed, as it looks like it's just a copy.

**Comment by mmeterel** [comment]
@jakub-homola Thanks for catching the error. 'k' should not be in the API syntax. We will remove it asap. We will also fix DPCPP documentation.

**Comment by mmeterel** [comment]
@jakub-homola #477 has fixed this issue in spec. We also updated [developer reference](https://www.intel.com/content/www/us/en/develop/documentation/oneapi-mkl-dpcpp-developer-reference/top/blas-routines/blas-level-2-routines/trsv.html) which should be reflected after next release. Thanks for reporting the issue.
