### ISSUE TITLE
Update css

### ISSUE THREAD

**Issue by outoftardis** [oneapi-src/oneAPI-spec#86]
Long lines of text do not wrap properly in a table, and the reader has to scroll to see content:
- [example №1](https://spec.oneapi.com/versions/latest/elements/oneTBB/source/algorithms/splittable_concept/proportional_split_cls.html#members)
- [example №2](https://spec.oneapi.com/versions/latest/elements/oneTBB/source/general/notation.html)

Related:

There are 2 css files with identical content:
- [in `/source/_static`](https://github.com/oneapi-src/oneapi-spec/blob/master/source/_static/custom.css)
- [in `/source/elements/oneTBB/source/_static`](https://github.com/oneapi-src/oneapi-spec/blob/master/source/elements/oneTBB/source/_static/custom.css)

It seems that the second one should be removed.

**Comment by rscohn2** [comment]
@outoftardis  Do you know how to update the css to wrap instead of scroll?

We can build the full doc or TBB standalone. I don't know how to share one directory for both. That is why it is duplicated.

**Comment by outoftardis** [comment]
> Do you know how to update the css to wrap instead of scroll?

Read the Docs's [instructions](https://rackerlabs.github.io/docs-rackspace/tools/rtd-tables.html)

**Comment by outoftardis** [comment]
> We can build the full doc or TBB standalone. I don't know how to share one directory for both. That is why it is duplicated.

I'd suggest to introduce a script into the building process that copies the main css file into the right directory each time the tbb is built as a standalone. Maybe at this point having two identical css files seems ok, but you are going to introduce changes to css over time, and this is additional work to have these changes implemented in two places each time. And what if other libraries would need this "build as a standalone" feature?

**Comment by rscohn2** [comment]
Having the script sync it should work well, and I can add the css at the same time. Thanks.

**Comment by rscohn2** [comment]
Adding @rsdubtso

**Comment by rscohn2** [comment]
The tables look ok now https://oneapi-src.github.io/oneAPI-spec/elements/oneTBB/source/notation.html
