### ISSUE TITLE
Update |*_full_name| for all components to include oneAPI

### ISSUE THREAD

**Issue by napetrov** [oneapi-src/oneapi-spec#87]
Currently all names mentioned without oneAPI prefix. So it’s not matching correct legal name and require addition of oneAPI in each case. 
Suggest to implement this for 0.8 version

**Comment by outoftardis** [comment]
Not all libraries use replacements from [common conf](https://github.com/oneapi-src/oneapi-spec/blob/master/source/conf/common_conf.py), meaning that this change should be accompanied by all elements incorporating the consistent usage of replacements in their docs.
